version: "3.8"

services:
  backend:
    container_name: to_do_list_backend
    build: ./
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - ./env/mysql_dev.env
    ports:
    - "3306:3306"
    volumes:
    - data:/var/lib/mysql

volumes:
  data: